### ISSUE TITLE
Check unbounded index range expression compilation

### ISSUE THREAD

**Issue by jmarton** [FTSRG/ingraph#306]
Once they are parsed in the grammar (slizaa/slizaa-opencypher-xtext#34), ensure they compile correctly.

**Comment by jmarton** [comment]
This has been superseded by (and fixed in) #344, also tests were added by @marci543.

**Comment by marci543** [comment]
The fix in slizaa/slizaa-opencypher-xtext@eaef8baee8d7415cc9ab647e1cc8816231910765 only describes variable-length paths. The index range expressions are defined elsewhere.
The https://github.com/FTSRG/ingraph/tree/hotfix-index-range-expression-306 branch adds a test for index range expressions at edf4858c5618467f2cf32256abad6c14c27d23a9.
The parsing error still occurs: https://travis-ci.org/FTSRG/ingraph/builds/408007001#L1643
